apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app-deployment
  labels:
    app: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: {{ .Values.imageName }}
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: env-secrets