version: '1'
services:
  dev_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS devdb; CREATE DATABASE IF NOT EXISTS sitdb;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345

