apiVersion: v1
kind: Service
metadata:
  labels:
    run: nestjs-app-svc-np
  name: nestjs-app-svc-np
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000 # กำหนดหมายเลข NodePort (30000-32767)
  selector:
    app: nestjs-app
  type: NodePort # เพิ่มเติมในส่วนของประเภทให้เป็น NodePort
